import { Candidate } from "../../types/index";

export const mockCandidates: Candidate[] = [
	{
		id: "1",
		name: "Aisha Patel",
		email: "aisha.patel@email.com",
		role: "Software Engineer",
		department: "Engineering",
		status: "submitted",
		availability: [
			{
				day: "Mon", date: "Jan 13",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: false },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: false },
					{ time: "3:00 PM", available: true },
				],
			},
			{
				day: "Tue", date: "Jan 14",
				slots: [
					{ time: "9:00 AM", available: false },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: false },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: true },
				],
			},
			{
				day: "Wed", date: "Jan 15",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: false },
					{ time: "11:00 AM", available: false },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: false },
				],
			},
			{
				day: "Thu", date: "Jan 16",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: false },
					{ time: "2:00 PM", available: false },
					{ time: "3:00 PM", available: true },
				],
			},
			{
				day: "Fri", date: "Jan 17",
				slots: [
					{ time: "9:00 AM", available: false },
					{ time: "10:00 AM", available: false },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: false },
				],
			},
		],
	},
	{
		id: "2",
		name: "Marcus Chen",
		email: "marcus.chen@email.com",
		role: "Academic Coordinator",
		department: "Academics",
		status: "submitted",
		availability: [
			{
				day: "Mon", date: "Jan 13",
				slots: [
					{ time: "9:00 AM", available: false },
					{ time: "10:00 AM", available: false },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: false },
				],
			},
			{
				day: "Tue", date: "Jan 14",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: false },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: false },
					{ time: "3:00 PM", available: true },
				],
			},
			{
				day: "Wed", date: "Jan 15",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: false },
					{ time: "2:00 PM", available: false },
					{ time: "3:00 PM", available: false },
				],
			},
			{
				day: "Thu", date: "Jan 16",
				slots: [
					{ time: "9:00 AM", available: false },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: false },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: true },
				],
			},
			{
				day: "Fri", date: "Jan 17",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: false },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: false },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: true },
				],
			},
		],
	},
	{
		id: "3",
		name: "Sofia Reyes",
		email: "sofia.reyes@email.com",
		role: "Software Engineer",
		department: "Engineering",
		status: "pending",
		availability: [],
	},
	{
		id: "4",
		name: "James Okafor",
		email: "james.okafor@email.com",
		role: "Software Engineer",
		department: "Engineering",
		status: "interviewed",
		availability: [
			{
				day: "Mon", date: "Jan 13",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: false },
					{ time: "3:00 PM", available: false },
				],
			},
			{
				day: "Tue", date: "Jan 14",
				slots: [
					{ time: "9:00 AM", available: false },
					{ time: "10:00 AM", available: false },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: false },
				],
			},
			{
				day: "Wed", date: "Jan 15",
				slots: [
					{ time: "9:00 AM", available: false },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: false },
					{ time: "1:00 PM", available: false },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: true },
				],
			},
			{
				day: "Thu", date: "Jan 16",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: false },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: false },
					{ time: "3:00 PM", available: true },
				],
			},
			{
				day: "Fri", date: "Jan 17",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: false },
					{ time: "1:00 PM", available: false },
					{ time: "2:00 PM", available: false },
					{ time: "3:00 PM", available: true },
				],
			},
		],
	},
	{
		id: "5",
		name: "Priya Nair",
		email: "priya.nair@email.com",
		role: "Academic Coordinator",
		department: "Academics",
		status: "submitted",
		availability: [
			{
				day: "Mon", date: "Jan 13",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: false },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: false },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: true },
				],
			},
			{
				day: "Tue", date: "Jan 14",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: false },
					{ time: "3:00 PM", available: false },
				],
			},
			{
				day: "Wed", date: "Jan 15",
				slots: [
					{ time: "9:00 AM", available: false },
					{ time: "10:00 AM", available: false },
					{ time: "11:00 AM", available: false },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: true },
				],
			},
			{
				day: "Thu", date: "Jan 16",
				slots: [
					{ time: "9:00 AM", available: true },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: false },
					{ time: "1:00 PM", available: false },
					{ time: "2:00 PM", available: true },
					{ time: "3:00 PM", available: false },
				],
			},
			{
				day: "Fri", date: "Jan 17",
				slots: [
					{ time: "9:00 AM", available: false },
					{ time: "10:00 AM", available: true },
					{ time: "11:00 AM", available: true },
					{ time: "1:00 PM", available: true },
					{ time: "2:00 PM", available: false },
					{ time: "3:00 PM", available: true },
				],
			},
		],
	},
];
