name: Developer Activity Tracker

on:
  schedule:
    # run every 3 days at midnight
    - cron: '0 0 */3 * *'
  workflow_dispatch:
    # allows manual triggering

jobs:
  track-activity:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv
      
      - name: run activity tracker
        run: python .github/scripts/activity_tracker.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          INACTIVITY_THRESHOLD_DAYS: 7
          NO_ISSUES_THRESHOLD_DAYS: 3
          # list of active developers to track (comma-separated)
          # if empty, all contributors will be tracked
          ACTIVE_DEVS: ${{ vars.ACTIVE_DEVS }} 